/**
 * Checks against the shared fixtures in test/fixtures (generated by tools/fixtures).
 */

import { PDFDocument, PDFName } from '@cantoo/pdf-lib';
import brokenXrefUrl from '../../../test/fixtures/broken-xref.pdf?url';
import taggedUrl from '../../../test/fixtures/tagged.pdf?url';
import xfaUrl from '../../../test/fixtures/xfa-stub.pdf?url';
import { afterAll, beforeAll, expect, test } from 'vitest';

import { PdfiumAdapter } from '../src/pdfium/pdfium-adapter';
import { PdfLibAssembler } from '../src/pdflib/pdflib-assembler';
import { sid, vdoc, vpage, wasmUrl } from './helpers';

const fetchBytes = async (url: string) => (await fetch(url)).arrayBuffer();
let adapter: PdfiumAdapter;

beforeAll(() => {
  adapter = new PdfiumAdapter({ wasmUrl });
});
afterAll(async () => {
  await adapter.destroy();
});

test('XFA and tagged sources are detected and reported as removed', async () => {
  const xfa = await fetchBytes(xfaUrl);
  const tagged = await fetchBytes(taggedUrl);
  const opened = await adapter.open(sid('xfa'), xfa.slice(0));
  expect(opened.flags.hasXfa).toBe(true);
  expect(opened.flags.hasAcroForm).toBe(true);
  await adapter.close(sid('xfa'));
  const taggedOpened = await adapter.open(sid('tagged'), tagged.slice(0));
  expect(taggedOpened.flags.tagged).toBe(true);
  await adapter.close(sid('tagged'));

  const result = await new PdfLibAssembler().assemble({
    document: vdoc([
      vpage({ kind: 'source', source: sid('xfa'), index: 0 }),
      vpage({ kind: 'source', source: sid('tagged'), index: 1 }),
    ]),
    sources: new Map([
      [sid('xfa'), xfa],
      [sid('tagged'), tagged],
    ]),
    blobs: new Map(),
  });
  expect(result.report.xfaRemoved).toBe(true);
  expect(result.report.structureTreeRemoved).toBe(true);
  const out = await PDFDocument.load(result.bytes, { updateMetadata: false, preserveXFA: true });
  expect(out.catalog.get(PDFName.of('StructTreeRoot'))).toBeUndefined();
  expect(out.catalog.get(PDFName.of('MarkInfo'))).toBeUndefined();
});

test('PDFium opens a file with a broken xref offset and it is flagged as repaired', async () => {
  const opened = await adapter.open(sid('broken'), await fetchBytes(brokenXrefUrl));
  expect(opened.pageCount).toBe(3);
  // PDFium repairs silently; the adapter's own xref check reports it (source-inspection.test).
  expect(opened.flags.repaired).toBe(true);
  await adapter.close(sid('broken'));
});
