/**
 * Signatures after the independent M5 engine review (spec recognize-and-compare §3,
 * ADR-0013): incremental-update attacks read through the xref chain (finding 1), document
 * timestamps (finding 2), the visual comparison of signed revisions (finding 3), PKCS#12 key
 * material wiped (finding 7), every SignerInfo checked and /DSS certificates in the chain
 * (finding 8). The attack and timestamp files are generated by tools/fixtures (m5-fixtures.ts).
 */
import { PDFDocument, PDFName } from '@cantoo/pdf-lib';
import * as asn1js from 'asn1js';
import * as pdfjs from 'pdfjs-dist/legacy/build/pdf.mjs';
import pdfjsWorkerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url';
import * as pkijs from 'pkijs';
import rsaUrl from '../../../test/fixtures/pki/signer-rsa.p12?url';
import { afterAll, afterEach, beforeAll, describe, expect, test, vi } from 'vitest';
import { commands } from 'vitest/browser';

import { PdfiumAdapter } from '../src/pdfium/pdfium-adapter';
import { derLength, fromHex, latin1 } from '../src/signatures/bytes';
import { loadPkcs12 } from '../src/signatures/pkcs12';
import { revisionBytes, validateSignatures } from '../src/signatures/validate';
import { revisionEnds } from '../src/signatures/xref';
import type { SignatureReport } from '../src/types';
import { createSignatureProxy } from '../src/worker/signature-proxy';
import { sid, wasmUrl } from './helpers';

function fromBase64(b64: string): Uint8Array<ArrayBuffer> {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
const fixture = async (name: string) =>
  fromBase64(await commands.readFile(`../../test/fixtures/${name}`, 'base64'));
const visual = { pdfiumWasm: wasmUrl } as const;
const check = (r: SignatureReport | undefined, id: string) => r?.checks.find((c) => c.id === id);
const MALLORY = 'PAY 1,000,000 TO MALLORY';
const PAGE_1 = 'PAGE 1 OF simple-text';

/** Page 1's text as pdf.js extracts it (a second reader, as Firefox would). */
async function pdfjsPage1(bytes: Uint8Array): Promise<string> {
  pdfjs.GlobalWorkerOptions.workerSrc = pdfjsWorkerUrl;
  const task = pdfjs.getDocument({ data: bytes.slice() });
  try {
    const doc = await task.promise;
    const content = await (await doc.getPage(1)).getTextContent();
    return content.items.map((item) => ('str' in item ? item.str : '')).join(' ');
  } finally {
    await task.destroy();
  }
}

/** The CMS of the signature whose byte range is `range`, parsed. */
function cmsOf(bytes: Uint8Array, range: readonly number[]): pkijs.SignedData {
  const [, b = 0, c = 0] = range;
  const padded = fromHex(latin1(bytes, b + 1, c - 1));
  const der = padded.subarray(0, derLength(padded) ?? padded.length);
  const info = new pkijs.ContentInfo({ schema: asn1js.fromBER(der.slice().buffer).result });
  return new pkijs.SignedData({ schema: info.content });
}

/** `bytes` with the CMS in the gap of `range` replaced (the gap is not signed). */
function withCms(bytes: Uint8Array, range: readonly number[], cms: pkijs.SignedData): Uint8Array {
  const [, b = 0, c = 0] = range;
  const der = new Uint8Array(
    new pkijs.ContentInfo({ contentType: '1.2.840.113549.1.7.2', content: cms.toSchema(true) })
      .toSchema()
      .toBER(),
  );
  let hex = '';
  for (const x of der) hex += x.toString(16).padStart(2, '0');
  hex = hex.toUpperCase().padEnd(c - b - 2, '0');
  expect(hex.length).toBe(c - b - 2);
  const out = bytes.slice();
  for (let i = 0; i < hex.length; i++) out[b + 1 + i] = hex.charCodeAt(i);
  return out;
}

/**
 * `bytes` plus one hand-written revision (uncompressed objects, a classic xref section, a
 * trailer continuing signed-approval.pdf's), as a writer that follows the rules would;
 * `unlisted` is written first and left out of the xref section.
 */
function appendRevision(
  bytes: Uint8Array,
  objects: { num: number; body: string }[],
  unlisted = '',
): Uint8Array {
  const prev = /startxref\s+(\d+)\s*%%EOF\s*$/.exec(latin1(bytes, bytes.length - 64))?.[1];
  let tail = unlisted;
  const xref: string[] = [];
  for (const { num, body } of objects) {
    xref.push(`${num} 1\n${String(bytes.length + tail.length).padStart(10, '0')} 00000 n \n`);
    tail += `${num} 0 obj\n${body}\nendobj\n`;
  }
  const at = bytes.length + tail.length;
  tail += `xref\n${xref.join('')}trailer\n<< /Size 20 /Root 2 0 R /Info 3 0 R /Prev ${prev} >>\nstartxref\n${at}\n%%EOF\n`;
  return new Uint8Array([...bytes, ...new TextEncoder().encode(tail)]);
}

const stream = (dict: string, data: string) =>
  `<< ${dict} /Length ${data.length} >>\nstream\n${data}\nendstream`;

describe('incremental-update attacks (review finding 1)', () => {
  let adapter: PdfiumAdapter;
  beforeAll(() => {
    adapter = new PdfiumAdapter({ wasmUrl });
  });
  afterAll(async () => {
    await adapter.destroy();
  });

  // What each reader shows on page 1, as measured: PDFium ignores the free entry and needs
  // %%EOF (so it falls back to the signed revision); pdf.js follows the xref in all three.
  const cases = [
    { file: 'signed-dup-object.pdf', pdfium: MALLORY, pdfjs: MALLORY, visual: [0] },
    { file: 'signed-freed-content.pdf', pdfium: PAGE_1, pdfjs: '', visual: [] },
    { file: 'signed-no-eof.pdf', pdfium: PAGE_1, pdfjs: MALLORY, visual: [] },
  ] as const;

  for (const want of cases) {
    test(`${want.file}: Changed after signing, page 1 content listed`, async () => {
      const bytes = await fixture(want.file);
      const [r] = await validateSignatures(bytes, { visual });
      expect(r?.status, JSON.stringify(r?.checks)).toBe('changed-after-signing');
      expect(check(r, 'digest')?.outcome).toBe('pass');
      expect(check(r, 'signature')?.outcome).toBe('pass');
      expect(check(r, 'later-changes')?.outcome).toBe('fail');
      expect(r?.laterChanges).toContainEqual({
        revision: 3,
        kind: 'content',
        pages: [0],
        objects: ['6 0 R'],
      });
      expect(r?.visuallyChangedPages).toEqual(want.visual);
      // The reason: a reader shows other text on page 1 than the signed revision.
      const id = sid(want.file);
      await adapter.open(id, bytes.slice().buffer);
      const pdfiumText = (await adapter.getPageText(id, 0)).map((run) => run.text).join(' ');
      await adapter.close(id);
      expect(pdfiumText).toContain(want.pdfium);
      const pdfjsText = await pdfjsPage1(bytes);
      if (want.pdfjs === '') expect(pdfjsText.trim()).toBe('');
      else expect(pdfjsText).toContain(want.pdfjs);
      // The signed revision itself shows the signed page and is Intact.
      const signed = new Uint8Array(revisionBytes(bytes, 2));
      expect(await pdfjsPage1(signed)).toContain(PAGE_1);
      expect((await validateSignatures(signed))[0]?.status).toBe('intact');
    });
  }

  test('signed-dup-object.pdf: the unreferenced second definition is a structural change', async () => {
    const [r] = await validateSignatures(await fixture('signed-dup-object.pdf'));
    expect(r?.laterChanges).toContainEqual({
      revision: 3,
      kind: 'other',
      pages: [],
      objects: ['6 0 R'],
    });
    expect(check(r, 'later-changes')?.detail).toMatch(/without listing it in its cross-reference/);
  });

  test('signed-no-eof.pdf: the revision without %%EOF counts as a revision', async () => {
    const bytes = await fixture('signed-no-eof.pdf');
    expect(revisionEnds(bytes).map((e) => e.end)).toEqual([2878, 20273, bytes.length]);
    const [r] = await validateSignatures(bytes);
    expect(r?.revisionCount).toBe(3);
  });

  test('page content that claims to be a signature, an annotation or an object stream is content', async () => {
    const approval = await fixture('signed-approval.pdf');
    const content = 'BT /Helvetica-7098480789 24 Tf 72 700 Td (PAY 1,000,000 TO MALLORY) Tj ET';
    for (const dict of [
      '/Type /Sig',
      '/Type /Annot /Subtype /Text /Rect [0 0 1 1]',
      '/Type /ObjStm',
    ]) {
      const bytes = appendRevision(approval, [{ num: 6, body: stream(dict, content) }]);
      const reports = await validateSignatures(bytes);
      const r = reports.find((x) => x.fieldName === 'Approval');
      expect(
        r?.status,
        `${dict}: ${JSON.stringify(reports.map((x) => [x.fieldName, x.status]))}`,
      ).toBe('changed-after-signing');
      expect(r?.laterChanges, dict).toEqual([
        { revision: 3, kind: 'content', pages: [0], objects: ['6 0 R'] },
      ]);
    }
    // The same revision written honestly as an annotation stays allowed.
    const note = appendRevision(approval, [
      { num: 14, body: '<< /Type /Annot /Subtype /Text /Rect [400 700 420 720] /P 5 0 R >>' },
    ]);
    expect((await validateSignatures(note))[0]?.status).toBe('intact-changed-later');
  });

  test('stray bytes, an xref pointing into the signed bytes, a broken chain: never Intact', async () => {
    const base = await fixture('signed-then-modified.pdf');
    const text = latin1(base);
    const signedEnd = 20273;
    // Junk between the signed revision and revision 3's objects.
    const junk = new Uint8Array([
      ...base.subarray(0, signedEnd),
      ...new TextEncoder().encode('junk\n'),
      ...base.subarray(signedEnd),
    ]);
    // (Offsets after the junk moved, so revision 3's xref no longer matches its objects.)
    const [a] = await validateSignatures(junk);
    expect(a?.status).toBe('changed-after-signing');
    // Revision 3's /Prev points at revision 1 instead of the signed revision 2.
    const prevAt = text.lastIndexOf('/Prev 19999');
    const skip = base.slice();
    new TextEncoder().encodeInto('/Prev  2500', skip.subarray(prevAt));
    const [b] = await validateSignatures(skip);
    expect(b?.status).toBe('changed-after-signing');
    expect(check(b, 'later-changes')?.detail).toMatch(/not back to the signed revision/);
  });
});

describe('second review: duplicate entries, early offsets, unreferenced objects', () => {
  let adapter: PdfiumAdapter;
  beforeAll(() => {
    adapter = new PdfiumAdapter({ wasmUrl });
  });
  afterAll(async () => {
    await adapter.destroy();
  });
  const pdfiumPage1 = async (bytes: Uint8Array) => {
    const id = sid('page-1');
    await adapter.open(id, bytes.slice().buffer);
    const text = (await adapter.getPageText(id, 0)).map((run) => run.text).join(' ');
    await adapter.close(id);
    return text;
  };
  /** `bytes` with `from` (first occurrence at or after `after`) replaced by `to`, same length. */
  const patch = (bytes: Uint8Array, from: string, to: string, after = 0): Uint8Array => {
    expect(to.length).toBe(from.length);
    const at = latin1(bytes).indexOf(from, after);
    expect(at).toBeGreaterThanOrEqual(after);
    const out = bytes.slice();
    new TextEncoder().encodeInto(to, out.subarray(at));
    return out;
  };
  const note = '<< /Type /Annot /Subtype /Text /Rect [400 700 420 720] /P 5 0 R >>';
  const statusOf = async (bytes: Uint8Array) => {
    const [r] = await validateSignatures(bytes);
    return r;
  };

  test('signed-dup-entry.pdf: two entries for page 1 content; pdf.js shows MALLORY, PDFium the signed page', async () => {
    const bytes = await fixture('signed-dup-entry.pdf');
    const [r] = await validateSignatures(bytes, { visual });
    expect(r?.status, JSON.stringify(r?.checks)).toBe('changed-after-signing');
    expect(check(r, 'digest')?.outcome).toBe('pass');
    expect(r?.laterChanges).toEqual([
      { revision: 3, kind: 'other', pages: [], objects: ['6 0 R'] },
    ]);
    expect(check(r, 'later-changes')?.detail).toMatch(/lists object 6 more than once/);
    expect(await pdfjsPage1(bytes)).toContain(MALLORY);
    const pdfium = await pdfiumPage1(bytes);
    expect(pdfium).toContain(PAGE_1);
    expect(pdfium).not.toContain(MALLORY);
    // The other order (the copy first, the replacement last): both findings are listed.
    const text = latin1(bytes);
    const xref = text.lastIndexOf('xref\n6 1\n');
    const [first = '', second = ''] = [...text.slice(xref).matchAll(/\d{10} 00000 n/g)].map(
      (m) => m[0],
    );
    const swapped = patch(patch(bytes, first, second, xref), second, first, xref + 30);
    const [s] = await validateSignatures(swapped);
    expect(s?.status).toBe('changed-after-signing');
    expect(s?.laterChanges).toEqual([
      { revision: 3, kind: 'content', pages: [0], objects: ['6 0 R'] },
      { revision: 3, kind: 'other', pages: [], objects: ['6 0 R'] },
    ]);
    expect(await pdfiumPage1(swapped)).toContain(MALLORY);
  });

  test('a repeated identical xref entry is harmless', async () => {
    const base = await fixture('signed-then-modified.pdf');
    const text = latin1(base);
    const xref = text.lastIndexOf('\nxref\n') + 1;
    const entry = /\n(14 1\n\d{10} 00000 n \n)/.exec(text.slice(xref))?.[1] ?? '';
    expect(entry).not.toBe('');
    const at = xref + text.slice(xref).indexOf(entry) + entry.length;
    const twice = new Uint8Array([
      ...base.subarray(0, at),
      ...new TextEncoder().encode(entry),
      ...base.subarray(at),
    ]);
    const r = await statusOf(twice);
    expect(r?.status).toBe('intact-changed-later');
    expect(r?.laterChanges).toEqual([
      { revision: 3, kind: 'annotations', pages: [0], objects: ['5 0 R', '14 0 R'] },
    ]);
  });

  test('signed-offset-early.pdf: an xref offset on whitespace or a comment before the header', async () => {
    const bytes = await fixture('signed-offset-early.pdf');
    const want = [{ revision: 3, kind: 'annotations', pages: [0], objects: ['5 0 R', '14 0 R'] }];
    const r = await statusOf(bytes);
    expect(r?.status, JSON.stringify(r?.checks)).toBe('intact-changed-later');
    expect(r?.laterChanges).toEqual(want);
    expect(await pdfjsPage1(bytes)).toContain(PAGE_1);
    // A comment instead of the spaces: readers skip it too.
    const comment = patch(bytes, '   5 0 obj', '%x\n5 0 obj', 20273);
    const c = await statusOf(comment);
    expect(c?.status).toBe('intact-changed-later');
    expect(c?.laterChanges).toEqual(want);
    // Anything else before the header is not skipped.
    const junk = await statusOf(patch(bytes, '   5 0 obj', 'xx 5 0 obj', 20273));
    expect(junk?.status).toBe('changed-after-signing');
  });

  test('unreferenced objects: listed; only a used number or possible content counts as a change', async () => {
    const approval = await fixture('signed-approval.pdf');
    const annot = [{ num: 14, body: note }];
    // A stray dictionary with a number no xref section uses: listed, still Intact, changed later.
    const stray = await statusOf(
      appendRevision(approval, annot, '99 0 obj\n<< /Junk (leftover) >>\nendobj\n'),
    );
    expect(stray?.status, JSON.stringify(stray?.checks)).toBe('intact-changed-later');
    expect(stray?.laterChanges).toEqual([
      { revision: 3, kind: 'annotations', pages: [0], objects: ['14 0 R'] },
      { revision: 3, kind: 'other', pages: [], objects: ['99 0 R'] },
    ]);
    expect(check(stray, 'later-changes')?.detail).toMatch(/unreferenced object 99 0 R/);
    // A number in use (page 1's content stream), or an object that could carry content.
    for (const unlisted of [
      '6 0 obj\n<< /Junk (leftover) >>\nendobj\n',
      '99 0 obj\n<< /Length 5 >>\nstream\nBT ET\nendstream\nendobj\n',
      '99 0 obj\n<< /Type /Page /Parent 7 0 R /MediaBox [0 0 612 792] >>\nendobj\n',
      '99 0 obj\n<< /Type /Annot /Subtype /Text /Rect [0 0 1 1] >>\nendobj\n',
      '99 0 obj\n<< /FT /Tx /T (x) >>\nendobj\n',
      '99 0 obj\n(trailer << /Root 20 0 R >>)\nendobj\n',
    ]) {
      const r = await statusOf(appendRevision(approval, annot, unlisted));
      expect(r?.status, unlisted).toBe('changed-after-signing');
      expect(check(r, 'later-changes')?.detail, unlisted).toMatch(/without listing it/);
    }
    // Garbage that is no object stays a change.
    const garbage = await statusOf(appendRevision(approval, annot, 'garbage\n'));
    expect(garbage?.status).toBe('changed-after-signing');
  });

  test("a revision's xref stream may not take a number an earlier revision uses", async () => {
    const approval = await fixture('signed-approval.pdf');
    const xrefStream = (num: number) => {
      const at = approval.length;
      const row = [1, (at >>> 24) & 255, (at >>> 16) & 255, (at >>> 8) & 255, at & 255, 0, 0];
      const head =
        `${num} 0 obj\n<< /Type /XRef /Size 30 /W [1 4 2] /Index [${num} 1] /Root 2 0 R` +
        ` /Info 3 0 R /Prev 19999 /Length ${row.length} >>\nstream\n`;
      return new Uint8Array([
        ...approval,
        ...new TextEncoder().encode(head),
        ...row,
        ...new TextEncoder().encode(`\nendstream\nendobj\nstartxref\n${at}\n%%EOF\n`),
      ]);
    };
    const fresh = await statusOf(xrefStream(20));
    expect(fresh?.status, JSON.stringify(fresh?.checks)).toBe('intact-changed-later');
    // Page 1's content stream number: a reader resolves 6 0 R to the xref stream.
    const taken = await statusOf(xrefStream(6));
    expect(taken?.status).toBe('changed-after-signing');
    expect(check(taken, 'later-changes')?.detail).toMatch(/takes the number 6/);
    // pdf-lib's own incremental save with object streams stays allowed.
    const doc = await PDFDocument.load(approval, {
      forIncrementalUpdate: true,
      updateMetadata: false,
    });
    const page = doc.getPage(2);
    const ref = doc.context.register(
      doc.context.obj({ Type: 'Annot', Subtype: 'Text', Rect: [10, 10, 30, 30] }),
    );
    page.node.set(PDFName.of('Annots'), doc.context.obj([ref]));
    const saved = await statusOf(await doc.commit({ useObjectStreams: true }));
    expect(saved?.status, JSON.stringify(saved?.checks)).toBe('intact-changed-later');
    expect(saved?.laterChanges.map((c) => c.kind)).toEqual(['annotations']);
  });
});

describe('visual comparison of the signed revision (review finding 3)', () => {
  test('signed-then-modified.pdf: the note draws on page 1, which the annotation change lists', async () => {
    const [r] = await validateSignatures(await fixture('signed-then-modified.pdf'), { visual });
    expect(r?.status).toBe('intact-changed-later');
    expect(r?.visuallyChangedPages).toEqual([0]);
    expect(r?.laterChanges).toEqual([
      { revision: 3, kind: 'annotations', pages: [0], objects: ['5 0 R', '14 0 R'] },
    ]);
    expect(check(r, 'later-changes')?.detail).toContain('page 1 looks different');
  });

  test('signed-twice.pdf (invisible second signature) and signed-then-changed.pdf', async () => {
    const [twice] = await validateSignatures(await fixture('signed-twice.pdf'), { visual });
    expect(twice?.status).toBe('intact-changed-later');
    expect(twice?.visuallyChangedPages).toEqual([]);
    const [changed] = await validateSignatures(await fixture('signed-then-changed.pdf'), {
      visual,
    });
    expect(changed?.status).toBe('changed-after-signing');
    expect(changed?.visuallyChangedPages).toEqual([0]);
  });

  test('without a renderer there is no visual result; a whole-file signature needs none', async () => {
    const [plain] = await validateSignatures(await fixture('signed-then-modified.pdf'));
    expect(plain?.visuallyChangedPages).toBeUndefined();
    const [whole] = await validateSignatures(await fixture('signed-approval.pdf'), { visual });
    expect(whole?.visuallyChangedPages).toBeUndefined();
  });

  test('the worker compares when its proxy is configured with pdfium.wasm', async () => {
    const proxy = createSignatureProxy(
      new Worker(new URL('../src/worker/signature.worker.ts', import.meta.url), {
        type: 'module',
      }),
      { pdfiumWasmUrl: wasmUrl },
    );
    try {
      const bytes = await fixture('signed-dup-object.pdf');
      const [r] = await proxy.validateSignatures(bytes.slice().buffer);
      expect(r?.status).toBe('changed-after-signing');
      expect(r?.visuallyChangedPages).toEqual([0]);
    } finally {
      proxy.terminate();
    }
  });
});

describe('document timestamps (review finding 2)', () => {
  test('signed-doctimestamp.pdf: the RFC 3161 token is Intact with its time and authority', async () => {
    const bytes = await fixture('signed-doctimestamp.pdf');
    const [approval, ts] = await validateSignatures(bytes);
    expect(approval?.status).toBe('intact-changed-later');
    expect(approval?.laterChanges.map((c) => c.kind)).toEqual(['signature']);
    expect(ts?.subFilter).toBe('ETSI.RFC3161');
    expect(ts?.status, JSON.stringify(ts?.checks)).toBe('intact');
    expect(ts?.timestamp).toEqual({
      time: '2024-01-03T00:00:00.000Z',
      tsa: 'CN=pdf-editor Test TSA,O=pdf-editor test PKI (not trusted)',
    });
    for (const c of ts?.checks ?? []) expect(c.outcome, `${c.id}: ${c.detail}`).toBe('pass');
    expect(check(ts, 'digest')?.detail).toMatch(/TSTInfo imprint \(SHA-256\) matches/);
    expect(check(ts, 'key-usage')?.detail).toMatch(/timeStamping/);
  });

  test('a byte flip in the timestamp’s range is Broken; an unknown CMS shape is Cannot check', async () => {
    const bytes = await fixture('signed-doctimestamp.pdf');
    const [, ts] = await validateSignatures(bytes);
    const [, b = 0, c = 0] = ts?.byteRange ?? [];
    for (const offset of [10, 3000, b - 20, c + 5]) {
      const flipped = bytes.slice();
      flipped[offset] = (flipped[offset] ?? 0) ^ 0x01;
      const reports = await validateSignatures(flipped);
      const same = reports.filter((r) => r.byteRange.join() === ts?.byteRange.join());
      for (const r of same) expect(r.status, `flip at ${offset}`).toBe('broken');
    }
    // Another SubFilter name and a token whose content type is not TSTInfo: never judged.
    const text = latin1(bytes);
    const odd = bytes.slice();
    const name = text.indexOf('/SubFilter /ETSI.RFC3161');
    new TextEncoder().encodeInto('/SubFilter /ETSI.RFC3999', odd.subarray(name));
    const tstOid = '060B2A864886F70D0109100104';
    const at = text.indexOf(tstOid, b);
    expect(at).toBeGreaterThan(b);
    odd[at + tstOid.length - 1] = '5'.charCodeAt(0);
    const [, unknown] = await validateSignatures(odd);
    expect(unknown?.status).toBe('cannot-check');
    expect(check(unknown, 'digest')?.detail).toMatch(/not supported/);
  });
});

describe('every SignerInfo, and /DSS certificates (review finding 8)', () => {
  const range = [0, 3335, 19721, 552];

  test('two signers that both verify: Cannot check; one that does not: Broken', async () => {
    const bytes = await fixture('signed-approval.pdf');
    const cms = cmsOf(bytes, range);
    const first = cms.signerInfos[0] as pkijs.SignerInfo;
    cms.signerInfos.push(new pkijs.SignerInfo({ schema: first.toSchema() }));
    const [both] = await validateSignatures(withCms(bytes, range, cms));
    expect(both?.status).toBe('cannot-check');
    expect(both?.checks.at(-1)?.detail).toMatch(/2 signers/);
    const bad = new Uint8Array(first.signature.valueBlock.valueHexView);
    bad[10] = (bad[10] ?? 0) ^ 0xff;
    const second = new pkijs.SignerInfo({ schema: first.toSchema() });
    second.signature = new asn1js.OctetString({ valueHex: bad.buffer });
    cms.signerInfos[1] = second;
    const [broken] = await validateSignatures(withCms(bytes, range, cms));
    expect(broken?.status).toBe('broken');
    expect(broken?.checks.at(-1)?.detail).toMatch(/Signer 2 does not verify/);
  });

  test('issuers found only in /DSS complete the chain', async () => {
    const bytes = await fixture('signed-approval.pdf');
    const cms = cmsOf(bytes, range);
    const certs = (cms.certificates ?? []) as pkijs.Certificate[];
    const leaf = certs.find((c) => c.serialNumber.valueBlock.valueDec === 0x3001);
    expect(leaf).toBeDefined();
    cms.certificates = [leaf as pkijs.Certificate];
    const leafOnly = withCms(bytes, range, cms);
    const [incomplete] = await validateSignatures(leafOnly);
    expect(check(incomplete, 'chain')?.outcome).toBe('fail');
    expect(incomplete?.status).toBe('intact');
    // A later revision adds /DSS with the intermediate and the root.
    const doc = await PDFDocument.load(leafOnly, {
      forIncrementalUpdate: true,
      updateMetadata: false,
    });
    const refs = certs
      .filter((c) => c !== leaf)
      .map((c) => doc.context.register(doc.context.stream(new Uint8Array(c.toSchema().toBER()))));
    doc.catalog.set(PDFName.of('DSS'), doc.context.register(doc.context.obj({ Certs: refs })));
    const withDss = await doc.commit({ useObjectStreams: false });
    const [r] = await validateSignatures(withDss);
    expect(r?.status).toBe('intact-changed-later');
    expect(r?.laterChanges.map((c) => c.kind)).toEqual(['dss']);
    expect(check(r, 'chain')?.outcome).toBe('pass');
    expect(check(r, 'chain')?.detail).toMatch(/2 of them from the document security store/);
    expect(r?.chain).toHaveLength(3);
  });

  test('issuer validity and CA facts are recorded', async () => {
    const [r] = await validateSignatures(await fixture('signed-approval.pdf'));
    expect(check(r, 'validity')?.detail).toMatch(/issuer certificates are valid at both times/);
    expect(check(r, 'chain')?.outcome).toBe('pass');
  });
});

describe('PKCS#12 key material is wiped (review finding 7)', () => {
  afterEach(() => {
    vi.restoreAllMocks();
  });

  test('the password bytes, the PKCS#8 plaintext and the imported DER are zero afterwards', async () => {
    const subtle = crypto.subtle;
    const importKey = subtle.importKey.bind(subtle);
    const decrypt = subtle.decrypt.bind(subtle);
    const pkcs8: Uint8Array[] = [];
    const passwords: Uint8Array[] = [];
    const plaintexts: Uint8Array[] = [];
    const view = (data: BufferSource) =>
      data instanceof ArrayBuffer
        ? new Uint8Array(data)
        : new Uint8Array(data.buffer, data.byteOffset, data.byteLength);
    vi.spyOn(subtle, 'importKey').mockImplementation(((
      format: KeyFormat,
      data: BufferSource,
      ...rest: [AlgorithmIdentifier, boolean, KeyUsage[]]
    ) => {
      if (format === 'pkcs8') pkcs8.push(view(data));
      if (format === 'raw' && rest[0] === 'PBKDF2') passwords.push(view(data));
      return importKey(format as 'raw', data, ...rest);
    }) as typeof subtle.importKey);
    vi.spyOn(subtle, 'decrypt').mockImplementation(async (...args) => {
      const out = await decrypt(...args);
      plaintexts.push(new Uint8Array(out));
      return out;
    });
    const id = await loadPkcs12(await (await fetch(rsaUrl)).arrayBuffer(), 'test-only');
    expect(id.key.extractable).toBe(false);
    const zero = (b: Uint8Array) => b.length > 0 && b.every((x) => x === 0);
    expect(pkcs8).toHaveLength(1);
    expect(zero(pkcs8[0] as Uint8Array)).toBe(true);
    expect(passwords.length).toBeGreaterThan(0);
    for (const p of passwords) expect(zero(p)).toBe(true);
    // The last decryption is the key bag's (the certificate bags come first).
    expect(zero(plaintexts.at(-1) as Uint8Array)).toBe(true);
  });
});
